# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2ba83ad619702330b29bc969737705436fa4345e9d710ab2d64a723218333e4eaddff54bba9a6b87e57ff9430b127ff85c69bfe645bf440a3101f209a13eece2

test:
  secret_key_base: 597f49f8d6d29480cf4c30bb5dc297a4c451cb6823e70abf144664895cb982a076fa4face7b5e2522f550acf95f2727e7f062e78ed2d4b0954c0399c613cdeeb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
